### PR TITLE
Merge deploy-forwarder-agent ops file with cf-d manifest

### PR DESCRIPTION
**Pull request by bradylove**
### WHAT is this change about?

Merge the [deploy-forwarder-agent ops-file](https://github.com/cloudfoundry/cf-deployment/blob/c0f3153563d919676271b744f626460d97b6f605/operations/experimental/deploy-forwarder-agent.yml) into cf-deployment.

### WHY is this change being made (What problem is being addressed)?

The forwarder agent and UDP forwarder agent are being added to make way for the new syslog architecture that will add another agent to each VM that will handle sending syslog messages for syslog CUPS bindings.

Instead of components writing directly to the loggregator agent they will write to the forwarder and UDP forwarder agents which have the same API as the loggregator agent. The UDP forwarder will forward logs to the forwarder agent, and the forwarder agent will forward logs to one or more downstream ports on the same VM. By default it is configured to forward to the loggregator agent.

Once the new syslog agent is ready we will add it with another downstream port to the forwarder agent.

### Please provide contextual information.

* [Tracker Label](https://www.pivotaltracker.com/n/projects/993188/search?q=label%3A%22%E2%88%9E%22)

### Has a cf-deployment including this change passed our [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [X] YES 
- [ ] NO

### How should this change be described in cf-deployment release notes?

Adds Loggregator forwarder and UDP forwarder agents in preparation for new syslog agent.

### Does this PR introduce a breaking change? 

No. The forwarder agent and UDP forwarder have the same API, listens on the same ports, and uses the same certificates as the loggregator agent.

### Will this change increase the VM footprint of cf-deployment?

- [ ] YES --- does it really have to?
- [X] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [X] experimental feature/component
- [X] GA'd feature/component

Moves experimental components to GA.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@MasslessParticle @jtuchscherer

### CODE REVIEW

**Comment by heyjcollins** [comment]
Hey @bradylove,

We usually like to see experimental features proven out on PWS before inlining to cf-deployment.
Is Cloudops already running with this configuration on PWS? If so, for how long?

Cheers,

Josh

**Comment by jtuchscherer** [comment]
@heyjcollins It is not running on PWS yet. The story to get it to PWS is here: https://www.pivotaltracker.com/n/projects/2090335/stories/162621548/comments/197788146

We can wait with pulling this in until PWS is running this.

**Comment by heyjcollins** [comment]
Thanks a lot @jtuchscherer - I'll block the PR on the tracker story you referenced above + a couple weeks to prove it's stable at scale.

Cheers,

Josh

**Comment by jtuchscherer** [comment]
@ab-pivot I might be missing some context here, but could you please let me know why this PR was closed? 
/cc @MasslessParticle

**Comment by cdutra** [comment]
@bradylove @jtuchscherer Is this ready to merge? Also could you resolve the conflicts, please? Thank you! :)

cc @davewalter

**Comment by jtuchscherer** [comment]
This PR can be closed. We created a new one. It was easier to create a new one than trying to keep this PR maintained. Here is the new one: https://github.com/cloudfoundry/cf-deployment/pull/750

**Pull request closed without merging**
