### PR TITLE
Add JWT certificate and signing alg

### PR DESCRIPTION
**Pull request by strehle**
## Please take a moment to review the questions before submitting the PR

🚫 We only accept PRs to develop branch. If this is an exception, please specify why 🚫

### WHAT is this change about?

New UAA key parameters for JWT:
signingAlg  -> https://tools.ietf.org/html/rfc7518#section-3.1 
signingCert -> https://tools.ietf.org/html/rfc7517#section-4.7

Acceptance UAA should have set this parameters to activate new behaviour.

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

no problem, but new feature

### Please provide any contextual information.

JWT token creation , see https://tools.ietf.org/html/rfc7518#section-3.1  and https://tools.ietf.org/html/rfc7517#section-4.7

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [X] YES
- [ ] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [X] NO

> **Types of breaking changes:**
> 1. **causes app or operator downtime**
> 2. increases VM footprint of cf-deployment - e.g. new jobs, new add ons, increases # of instances etc.
> 3. modifies, deletes or moves the name of a job or instance group in the main manifest
> 4. modifies the name or deletes a property of a job or instance group in the main manifest
> 5. changes the name of credentials in the main manifest
> 6. requires out-of-band manual intervention on the part of the operator
> 7. modifies the ops-file path, changes the type, changes the values or removes ops-files from the following folders
>    - `./operations/` or `./operations/experimental`
>    - `./addons`
>    - `./backup-and-restore/`
>
> _If you're promoting an experimental Ops-file (or removing one), Please follow the [Ops-file workflows](https://github.com/cloudfoundry/cf-deployment/blob/main/ops-file-promotion-workflow.md)._

> Ops files changes in the following folders are considered as NON BREAKING CHANGES
> `./community`, `./example-vars-files`, `./test`

### How should this change be described in cf-deployment release notes?

> _Something brief that conveys the change and is written with the **persona (Alana, Cody...)** in mind. See [previous release notes](https://github.com/cloudfoundry/cf-deployment/releases) for examples._

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [X] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [X] GA'd feature/component

### Please provide Acceptance Criteria for this change?

New UAA in /token_keys show xt5 claim with the certificate as trust anchor , e.g. https://login.uaa-acceptance.cf-app.com/token_keys

> _Few examples_
> 1. For a PR with a new job in the manifest, `bosh instances` can verify the job is running after upgrade. You can provide additional commands to verify the job is running as specified.
> 2. For a PR with new variables, `bosh variables | grep <var-name>` command can verify the variable exists. This is the simplest varification but you can also provide additional commands to test that the variable holds the desired value.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

UAA -> https://github.com/cloudfoundry/uaa

### CODE REVIEW

**Comment by jochenehret** [comment]
Is this really no breaking change? This PR basically changes the type of a BOSH variable (from "rsa" to "certificate"). What does this mean for existing deployments? Can BOSH update the credential? Do we need any intermediate steps to update the UAA instances?

**Comment by strehle** [comment]
> Is this really no breaking change? This PR basically changes the type of a BOSH variable (from "rsa" to "certificate"). What does this mean for existing deployments? Can BOSH update the credential? Do we need any intermediate steps to update the UAA instances?

Hi , the uaa_jwt_signing_key should be a certificate yes similar to SAML config. The private key is the only required config; the cert is optional for UAA Startup therefore I see this change as non breaking.

**Comment by jochenehret** [comment]
Ok so from UAA perspective this would not be a breaking change. But what about BOSH and CredHub? If someone has already a "rsa" credential in CredHub and now we change it to "certificate", will BOSH automatically change the type?

**Comment by strehle** [comment]
> Ok so from UAA perspective this would not be a breaking change. But what about BOSH and CredHub? If someone has already a "rsa" credential in CredHub and now we change it to "certificate", will BOSH automatically change the type?

@bruce-ricard @peterhaochen47 can you help about credhub behavior? I found https://github.com/cloudfoundry/credhub/blob/main/docs/credential-types.md , so from my understanding change from rsa to certificate is no breaking change, because field private_key is in both types available and this is what UAA really needs . The existence of certificate is optional.

**Comment by ae-govau** [comment]
Hmm, this changes something that was previously a key to something that is now a certificate. Amongst other things, certificates have expiration dates...

What does BOSH do when it sees a variable declared that exists but is the wrong type? I bet it's not documented. Is it different if credhub is used? Is that documented?

I worry that at best this change is brittle and it's not clear what benefit it brings? Section 4.7 referenced above is an optional field - it's not required to be returned.

**Comment by davewalter** [comment]
Would it make sense to simply change the name of the variable as part of this PR? This should cause BOSH to generate a new certificate.

**Comment by strehle** [comment]
> Reference

please see https://github.com/cloudfoundry/cf-deployment/pull/1079/commits/a0f6421577fa854d7c44f7aeedef5609013ed13d so with that we have 2 keys in OIDC but key-1 is not touched at all. Key2 is created with the X509 enhancements

x5t in the JSON Web Keys is something which is used by Microsoft but its usage is in standard defined. We need it in UAA to perform OIDC calls towards Azure AD without secrets.
Otherwise UAA would have to store a secret from Azure AD in UAA DB. The client authentication mechanism https://oauth.net/private-key-jwt/ allows to omit secrets. The x5t from UAA needs to be stored in Azure AD, then Azure trusts a UAA. If UAA has the certificate we add the x5t, see others approach https://github.com/OpenIDC/mod_auth_openidc/discussions/762

finally, MS documentation https://learn.microsoft.com/en-us/azure/active-directory/develop/certificate-credentials .

**Comment by strehle** [comment]
> I worry that at best this change is brittle and it's not clear what benefit it brings? Section 4.7 referenced above is an optional field - it's not required to be returned.

You can say that the big companies are brittle, yes, but is part of the standard. If you want omit secrets and integrate Azure AD then you have to do this.
I want to show others with that what UAA is able to do. If you customize your bosh deployment you can do this already on your own. The OIDC integration has the advantage, that you can replace SAML and LDAP because OIDC allows the browser and password (API) flows and you can link your UAA to your corporate Azure.

**Comment by jochenehret** [comment]
Using a new credential should cause less problems for the transition. We'll discuss this PR in tomorrow's ARD WG meeting.

**Review by jochenehret — APPROVED** [review]

**Pull request merged**
