### PR TITLE
operations/deploy-forwarder-agent:

### PR DESCRIPTION
**Pull request by johncornish**
add forwarder agent and udp forwarder to cf-deployment

[#161354025]

### WHAT is this change about?

Deploy forwarder agent and udp forwarder

### WHY is this change being made (What problem is being addressed)?

Operators need an easy way to deploy the new forwarder agent with cf-deployment

### Please provide contextual information.

Story: [https://www.pivotaltracker.com/story/show/161354025](https://www.pivotaltracker.com/story/show/161354025)

### Has a cf-deployment including this change passed our [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES 
- [x] NO

### How should this change be described in cf-deployment release notes?

Operators can now deploy and test the new forwarder agent

### Does this PR introduce a breaking change? 

It shouldn't

### Will this change increase the VM footprint of cf-deployment?

- [ ] YES --- does it really have to?
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [ ] GA'd feature/component

What is GA?

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
I soloed on this

### CODE REVIEW

**Comment by heyjcollins** [comment]
Hey @johncornish,

I'm not sure if this was intentional or not, but since this was closed here I've deleted the story it generated in our backlog.
If you still want to submit this PR, please resubmit whenever you're ready.

Thanks!

Josh

**Comment by johncornish** [comment]
Forgot to run tests and check if it would deploy last time

**Comment by ab-pivot** [comment]
This PR has been separately merged to the develop branch under the following commits
- ac1e93952004b3a60d655b89e4951398a1d4c6c2
- dc76b11a4a22ba72157824056eab38ecada412f5

GitHub failed to recognize the merge due to merge conflicts, which we resolved, so we are manually closing this PR.

**Comment by bradylove** [comment]
@aegershman Me and @tomcharles updated this PR for some changes that were made to the forwarder agent in `loggregator-agent-release` v3.2.

The use case for this is to support multiple agents living on each VM. Out of the box the forwarder agent will act like the existing loggregator agent, but will forward to one or more down stream services.

This is mainly to support changes we are making to the syslog system, where we will have an agent along side each loggregator-agent that is responsible for sending logs to syslog endpoints.

**Pull request merged**
