### PR TITLE
Add support for alicloud blobstore

### PR DESCRIPTION
**Pull request by xiaozhu36**
This PR aims to support alibaba cloud oss blobstore and it has a pre-PR #531 .

### CODE REVIEW

**Comment by heyjcollins** [comment]
Thanks for submitting this PR. We are about to publish cf-deployment 2.0 next week and the 2.0 release alters the way external blob stores are configured in the deployment. You may want to review the upcoming changes in the release-candidate branch and update this PR as necessary so it aligns with the new approach. Feel free to reach out on the cloudfoundry #cf-deployment Slack channel if you have any questions or need support.

**Comment by heyjcollins** [comment]
Hey @xiaozhu36 -- 
I've reviewed the changes in this PR and would love to publish them and have a few change requests/issues that I'm hoping you can resolve: 
1. The PR includes a change duplicated in [PR #531](https://github.com/cloudfoundry/cf-deployment/pull/531/files). Could you please close PR #531 since it's redundant.
1. Reference a production release of CAPI.
   - the current PR references a dev release of CAPI: `1.60.0.dev` rather than a [release that's been verified and published](https://github.com/cloudfoundry/capi-release/releases) by the CAPI team.
1. The file names and references in the files and the README content include `oss`. Would you consider making an update to this as it may be clearer to operators since the Alibaba Cloud Object Storage Service brand name is not as widely known as other names in the cloud storage space.? Perhaps `alibaba-cloud-oss` or `alicloud-oss` would be acceptable? 
   - if you could update the all references to `oss` in content and filenames would be helpful. For example: 
   - `use-oss-blobstore.yml` --would be changed to-- `use-alibaba-cloud-oss-blobstore.yml`
   - `vars-use-oss-blobstore.yml` --would be changed to-- `vars-use-alibaba-cloud-oss-blobstore.yml`
   - etc...
1. `use-oss-blobstore.yml` includes a comment referring to a [cloud_controller_ng PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/1147) which has now been merged to master so this comment can now be removed.

**Comment by xiaozhu36** [comment]
Hi @heyjcollins Thanks for your review and I have improved the PR according to your suggestion. Please check it. Thanks a lot.

**Comment by xiaozhu36** [comment]
Hi @heyjcollins Thanks for your review and I have improved the PR according to your suggestion. Please check it, thanks a lot.

**Comment by heyjcollins** [comment]
Hi @xiaozhu36  - Thanks for making these changes. I'll pull this PR into our backlog!

**Pull request merged**
