### PR TITLE
Add secure-service-credentials ops file

### PR DESCRIPTION
**Pull request by ishustava**
This PR adds an ops file, which enables secure service credentials delivery with CredHub.

### CODE REVIEW

**Comment by pivotal-danjahner** [comment]
This ops file is missing a property to enable CC > Diego communication. This should be added - 

```
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/temporary_local_apps
  value: true
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/temporary_local_tasks
  value: true
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/temporary_local_staging
  value: true
```

**Comment by ishustava** [comment]
@pivotal-danjahner

What we haven't mentioned is that this ops file has a dependency on `bypass-cc-bridge.yml` ops file in cf-deployment which accomplishes that. Whiteout that ops file CATs were not passing. We have [documented it in the `credhub-release` repo](https://github.com/pivotal-cf/credhub-release/blob/master/docs/secure-service-credentials.md)

**Comment by dsabeti** [comment]
@ishustava @pivotal-danjahner Just a heads up, when we merge this PR, we're going to add functionality to our pipeline to update the release version automatically when new credhub releases are shipped. Let us know if there's a problem with that approach.

**Comment by pivotal-danjahner** [comment]
Sounds good.

**Pull request merged**
