### PR TITLE
set enable_comma_delimited_destinations to true

### PR DESCRIPTION
**Pull request by ameowlia**
### WHAT is this change about?

This change will allow operators to create ASGs with a _list_ of ips instead of just one ip or a cidr.

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

It is annoying to create multiple ASGs for each ip or cidr.

### Please provide any contextual information.

[CAPI PR (includes links to other PRs)](https://github.com/cloudfoundry/cloud_controller_ng/pulls?q=is%3Apr+comma)
[Docs PR](https://github.com/cloudfoundry/docs-cloudfoundry-concepts/pull/201)

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [x] YES
- [ ] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [x] NO

### How should this change be described in cf-deployment release notes?

Operators can create ASGs with comma-delimited destinations. For example, the following ASG definition is valid:
```
[
 {
   "protocol": "tcp",
   "destination": "1.2.3.4,10.0.0.0/24,25.0.0.0-26.0.0.0",
   "ports": "65432",
   "description": "Valid comma delimited list of destinations"
 }
]
```

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [x] GA'd feature/component

### Please provide Acceptance Criteria for this change?
It should pass this [CAT](https://github.com/cloudfoundry/cf-acceptance-tests/blob/main/security_groups/comma_delmited_asgs.go). You can run this cat by setting the [new CAT config value](https://github.com/cloudfoundry/cf-acceptance-tests/blob/6a54fe5064a29c09ca6c7a8ee5ffa2a1bf5698d6/README.md?plain=1#L130) `comma_delim_asgs_enabled` to true. 

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### CODE REVIEW

**Comment by ameowlia** [comment]
Before merging this PR you should run its related [CAT](https://github.com/cloudfoundry/cf-acceptance-tests/blob/main/security_groups/comma_delmited_asgs.go) in your pipelines by setting the [new CAT config value](https://github.com/cloudfoundry/cf-acceptance-tests/blob/6a54fe5064a29c09ca6c7a8ee5ffa2a1bf5698d6/README.md?plain=1#L130) `comma_delim_asgs_enabled` to true.

**Comment by jochenehret** [comment]
Enabling new CATs on luna/trelawney: https://github.com/cloudfoundry/relint-envs/pull/42

**Review by jochenehret — APPROVED** [review]

**Comment by jochenehret** [comment]
Test for comma-delimited ASGs is failing as expected: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/fresh-cats/builds/1403
Next run should be green.

**Comment by ameowlia** [comment]
It went green! Yay! Thank you @jochenehret.

**Pull request merged**
