### PR TITLE
inlined enable-routing-integrity.yml into cf-deployment.yml

### PR DESCRIPTION
**Pull request by n4wei**
[#161142258](https://www.pivotaltracker.com/story/show/161142258)

Co-authored-by: Maria Shaldibina <mshaldibina@pivotal.io>

### Is this a PR to [the develop branch](https://github.com/cloudfoundry/cf-deployment/tree/develop) of cf-deployment?

Yes

### WHAT is this change about?

This is a breaking change that makes route integrity default in cf-deployment intended for the next major version of cf-d. This other PR https://github.com/cloudfoundry/cf-deployment/pull/745 is related and allows operator to opt out of routing integrity via a new operations file.

### WHY is this change being made (What problem is being addressed)?

We would like to make app traffic more secure by turning route integrity on by default.

### Please provide contextual information.

Tracker story: https://www.pivotaltracker.com/story/show/161142258
PR to opt out of route integrity: https://github.com/cloudfoundry/cf-deployment/pull/745
Subsequent PR to remove the deprecated ops file: https://github.com/cloudfoundry/cf-deployment/pull/753

### Has a cf-deployment including this change passed our [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES 
- [X] NO

### How should this change be described in cf-deployment release notes?

By default, enables container proxy on the Diego Cell rep and configures gorouter to opt into TLS-enabled connections to the backend.

### Does this PR introduce a breaking change? 

Yes. It is intended for the next major version of cf-d.
- changes cf-deployment.yml

### Will this change increase the VM footprint of cf-deployment?

- [ ] YES --- does it really have to?
- [X] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [X] GA'd feature/component

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@cf-diego

### CODE REVIEW

**Comment by Syerram** [comment]
@n4wei Deprecation of ops files is two part process. You can find the flow [here](https://github.com/cloudfoundry/cf-deployment/blob/master/ops-file-promotion-workflow.md). 

Basically, you replace the entire ops file with one word `#DEPRECATED` and PR the change. We will release that as a minor release with the deprecation notice that we will remove this ops file in the next major release. 

Also, does the change in `cf-deployment.yml` introduce breaking change?

**Comment by sunjayBhatia** [comment]
@Syerram this is a significant change we would expect to be desirable to make in the next *major* version of cf-d

**Comment by mariash** [comment]
We updated the PR with `#DEPRECATED` comment and left the ops file. We made another PR to remove the ops file in subsequent step: https://github.com/cloudfoundry/cf-deployment/pull/753

**Comment by mariash** [comment]
@cf-rel-int-status-bot I think the test needs to be updated since there is a change to cf-deployment?

**Comment by davewalter** [comment]
Hi @mariash,

Could you please include the fix to the tests in the PR? Also, since this is a breaking change, I think we won't be able to pull it in until v9 at this point.

Thanks,
Dave

CC @Syerram

**Pull request merged**
