### PR TITLE
Enable TLS between route-emitter and NATS

### PR DESCRIPTION
**Pull request by mariash**
### WHAT is this change about?

Add an ops-file to enable communication over TLS between Diego route-emitter and NATS.

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

Adds security when route-emitter is communicating to NATS.

### Please provide any contextual information.

https://www.pivotaltracker.com/story/show/170136376

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES
- [X] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [X] NO

### How should this change be described in cf-deployment release notes?

Added an ops-file to enable TLS between route-emitter and NATS.

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [X] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [X] GA'd feature/component

### Please provide Acceptance Criteria for this change?

1. Apply dependent ops-file `operations/enable-nats-tls.yml` from this PR: https://github.com/cloudfoundry/cf-deployment/pull/853 and provided ops-file `operations/enable-route-emitter-nats-tls.yml`
2. `bosh ssh` to any diego-cell VM
3. Run `netstat -anop | grep route | grep '4222\|4224'` and see that route-emitter is connecting to NATS over `4224` port which is served by `nats-tls` job.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@cf-diego

### CODE REVIEW

**Comment by acosta11** [comment]
Hello @mariash ,

Thanks for the clear acceptance criteria instructions! I was able to deploy and see the nats-tls reserved port in use on the deployment's diego cells. However, I'm having some issues getting two tests passing in CATs.

```
[Fail] [service discovery] Service Discovery Adding an internal route on an app [It] successfully creates a policy
[Fail] [route_services] Route Services when a route binds to a service when service broker returns a route service url [It] a request to the app is routed through the route service
```

Did you happen to get a chance to run CATs against the new tls job as it's configured? And would there possibly be some other configuration I would need for the new functionality?

Thanks,
Andrew

**Comment by mariash** [comment]
@acosta11 these are the group of tests we don't run in our CI. I will try to reproduce it and let you know.

**Comment by mariash** [comment]
@acosta11 the [service_discovery] test failed for me on the first run with the following error:
```
cf map-route CATS-1-APP-BACK-c89ddc3fe349b128 apps.internal --hostname CATS-1-HOST-41c8831b15440984
FAILED
Domain apps.internal not found
```

I manually created a domain and rerun the test and it passed:
`cf create-shared-domain apps.internal --internal`

I don't know why this is not documented or not the part of the test setup.

**Comment by mariash** [comment]
@acosta11 the [service_discovery] test failed for me on the first run with the following error:
```
cf map-route CATS-1-APP-BACK-c89ddc3fe349b128 apps.internal --hostname CATS-1-HOST-41c8831b15440984
FAILED
Domain apps.internal not found
```

I manually created a domain and rerun the test and it passed:
`cf create-shared-domain apps.internal --internal`

I don't know why this is not documented or not the part of the test setup.

Update: that test suite requires this ops-file https://github.com/cloudfoundry/cf-deployment/blob/master/operations/enable-service-discovery.yml

Please let me know if this test fails for you the same way and this setup helped?

**Comment by mariash** [comment]
Hi @acosta11, considering [route_services] failure it did fail for me with the following error:

```
Timed out after 240.000s.
        Expected process to exit.  It did not.ESC[0m

        /home/pivotal/workspace/cf-acceptance-tests/route_services/route_services.go:54
```

So I noticed that the part that is timing out is `cf push`. I tried to manually push this golang app and the time I got was:
```
real    7m58.745s
user    0m1.139s
sys     0m0.082s
```
During push you can see that it took a very long time for staging process to download go 1.13.5. 

I ran acceptance test with the following configuration:
`"cf_push_timeout": 600`

After this setting the push succeeded but test failed:
```
Waiting for:
            Response Body: go, world
```

Looking closer at the error, the app was returning: `526 Invalid SSL Certificate`

I reverted applied ops-files for nats TLS but I was still getting the same failure on this test. Is it true for you as well?

I asked in the routing channel about this failure https://cloudfoundry.slack.com/archives/CFX13JK7B/p1579133959072400 

Would be nice to make this test pass eventually. But at this point it seems unrelated to NATs TLS enablement.

**Comment by mariash** [comment]
@acosta11 the test [route_services] passed for me after applying an ops-file https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-internal-lookup-for-route-services.yml

**Pull request merged**
