### PR TITLE
Update routers in serial

### PR DESCRIPTION
**Pull request by shashwathi**
This PR will enable routers to update serially and not in parallel. 

Regards
Shash

### CODE REVIEW

**Comment by cppforlife** [comment]
out of curiosity why make them serial?

**Comment by anEXPer** [comment]
This is a great change. Thanks! How did you come to notice it, out of curiosity?

**Comment by anEXPer** [comment]
@cppforlife, how else would you suggest avoiding app downtime while rolling the routers?

**Comment by cppforlife** [comment]
as long as max_in_flight is configured appropriately you are fine. moreover, max in flight is also scoped to within an az so currently routers will be updated one at time even though max in flight is 5.

**Comment by anEXPer** [comment]
Maybe I'm not understanding, but if max-in-flight is per-AZ, doesn't that mean that each AZ can be rolling up to 1 instance at a time, so if each AZ only _has_ one instance, max-in-flight doesn't keep them from going at the same time at all?

**Comment by anEXPer** [comment]
We found this created unexpected issues, because router needs UAA to come up, and it wasn't.

We didn't think through what the `serial: true` property actually does. If we really want this, we need to re-order how the jobs deploy. We might want to do that anyway.

**Comment by shashwathi** [comment]
@anEXPer : 

If routing api is enabled, `gorouter` tries to connect to UAA to obtain token to connect to API server and this required UAA to be up and running before gorouter.
We probably did not encounter this before because UAA came up along with gorouter.

> If we really want this, we need to re-order how the jobs deploy. 

I agree with that change. Do you need PR from the routing team or XTP with us?  We are currently blocked on this change so we would get this change in cf-deployment ASAP.

Regards
Shash

**Pull request merged**
