### PR TITLE
Enables BPM for Cloud Controller jobs

### PR DESCRIPTION
**Pull request by elenasharma**
We'd like to enable BPM for Cloud Controller jobs as part of the effort to default to BPM.

[#152820217]

### CODE REVIEW

**Comment by zrob** [comment]
Please do not merge this.  BPMed CC does not behave well when the blobstore is nfs

**Comment by dsabeti** [comment]
@zrob Ok, sounds good. Are we waiting for an update to this ops-file or a new capi-release before merging this?

**Comment by zrob** [comment]
waiting on this https://www.pivotaltracker.com/story/show/157880726

**Comment by heyjcollins** [comment]
any update on this?

**Comment by zrob** [comment]
still waiting on the linked story.  it's working its way up the backlog

**Comment by heyjcollins** [comment]
@zrob - looks like this PR is unblocked. Now that BPM is enabled on every instance group, could you just update CC to use it, rather than using this experimental ops file to enable?

**Comment by ishustava** [comment]
@heyjcollins @zrob 

We'll go ahead and merge this PR and inline these properties as part of this story: https://www.pivotaltracker.com/story/show/158133748

**Pull request merged**
