### PR TITLE
Loggregator iso segments

### PR DESCRIPTION
**Pull request by poy**
### WHAT is this change about?

Add ops files to deploy an isolated Loggregator.

### WHY is this change being made (What problem is being addressed)?

To enable isolated Loggregator

### Please provide contextual information.

https://www.pivotaltracker.com/story/show/160112181

### Has a cf-deployment including this change passed our [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [x] YES 
- [ ] NO

### How should this change be described in cf-deployment release notes?

- Adds ops files to deploy isolated Loggregator and Syslog Drains

### Does this PR introduce a breaking change? 

No

### Will this change increase the VM footprint of cf-deployment?

- [x] YES
- [ ] NO

If the ops files are used, a whole isolated Loggregator will deployed

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [x] GA'd feature/component

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
@MasslessParticle @jtuchscherer

### CODE REVIEW

**Comment by ishustava** [comment]
Hey @poy,

Looks like some of our unit tests are failing because some files were deleted. Would you mind taking a look and updating this PR?

Also, we're seeing that you've modified `operations/experimental/infrastructure-metrics.yml` with a link, but we're not sure whether it's related to the change intended in this PR.

Thanks!
Iryna & @vitreuz

**Comment by poy** [comment]
@ishustava @vitreuz I have updated the PR.

@heyjcollins It looks like removing consul files crept into this PR somehow: https://github.com/cloudfoundry/cf-deployment/commit/4762383. I removed it to get the tests passing. However, it looks like you have an [accepted story](https://www.pivotaltracker.com/n/projects/1382120/stories/160663517) that references it.

**Comment by heyjcollins** [comment]
Hey @poy - regarding your previous comment:
The accepted story you found is for replacing the contents of those consul files with a deprecation message. This is the first step of the deprecation process. Those files will be deleted in the next major release so i think it's fine that you've removed those references from `operations/test/add-persistent-isolation-segment-infrastructure-metrics.yml` and `operations/test/add-persistent-isolation-segment-syslog-drain.yml`.

**Comment by heyjcollins** [comment]
Hey @poy,

Just following up to see if you're going to finish with the changes as per the code review from RelInt?

Would love to move this along and out of our backlog.

Thanks!

Josh

**Comment by poy** [comment]
@MasslessParticle do you mind weighing in on this?

**Comment by MasslessParticle** [comment]
We'll chat about it today. Some of the requested changed introduced more work than we could manage last week.

**Comment by MasslessParticle** [comment]
@heyjcollins We've made the requested changes to the PR!

**Pull request merged**
