### PR TITLE
Add Credhub Migration to enable-nfs-volume-service Ops File

### PR DESCRIPTION
**Pull request by davewalter**
### WHAT is this change about?

We have updated the `enable-nfs-volume-service.yml` ops-file to include a migration to switch the backing store for the `nfsbroker` app from SQL to Credhub.

### WHY is this change being made (What problem is being addressed)?

We are deprecating support for regular databases in favour of Credhub as we often have to store credentials as part of service instance configuration and bindings.

### Please provide contextual information.

[#161974894](https://www.pivotaltracker.com/story/show/161974894)

### Has a cf-deployment including this change passed our [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES 
- [X] NO

However, this has passed Persi's acceptance tests.

### How should this change be described in cf-deployment release notes?

The NFS volume service has been updated to natively support Credhub as its backing store. As part of this, it also includes a migration that will run the first time the nfsbrokerpush errand is run after deploying CF with this updated ops file applied. This will retire the existing SQL database and move all service instance and binding metadata into the Credhub database. The SQL database will *not* be removed automatically, but will no longer be used once the `nfsbrokerpush` errand has successfully completed.

We also deleted the experimental `enable-nfs-volume-service-credhub.yml` ops-file as this is now surplus to requirements.

### Does this PR introduce a breaking change? 

Yes. The removal of the `enable-nfs-volume-service-credhub.yml ` ops-file is a breaking change for anyone that was using it.

### Will this change increase the VM footprint of cf-deployment?

- [ ] YES --- does it really have to?
- [X] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [X] experimental feature/component
- [X] GA'd feature/component

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
@paulcwarren @julian-hj

### CODE REVIEW

**Comment by davewalter** [comment]
Please note that this PR contains a single-line conflict with https://github.com/cloudfoundry/cf-deployment/pull/715 in that both delete the same line from `scripts/test-experimental.sh`. We did this to avoid a dependency between the two PRs, but wanted to eliminate any surprise that might arise from a conflict when merging the PRs.

**Comment by heyjcollins** [comment]
Thanks Dave,

I assume operators may decide copy and/or delete the deprecated mySQL db after gaining confidence in the migration to CredHub.

Could you provide steps for doing so to this PM so we can add them to release notes.

- cc @Syerram (Sai is rolling on as RelInt PM so I'll be including him on all communications going forward).

**Comment by paulcwarren** [comment]
Hi @heyjcollins,

Here are some commands for backing-up and deleting the `nfs-broker`SQL database from an internal MySQL server.

1. `bosh -d cf ssh database`
1. `/var/vcap/packages/pxc/bin/mysqldump --defaults-extra-file=/var/vcap/jobs/pxc-mysql/config/mylogin.cnf nfs-broker > nfs.sql` (to dump the database to a file)
1. `/var/vcap/packages/pxc/bin/mysql --defaults-extra-file=/var/vcap/jobs/pxc-mysql/config/mylogin.cnf -e "DROP DATABASE nfs-broker;"` (to delete the database)

These commands assume that no customization has been performed by the operator (such as renaming the database instance or the nfs-broker database). If the operator is using an external database, they will have to connect to it using their existing credentials and perform the corresponding steps.

Let us know if you have more questions.

Regards
Paul and @davewalter

**Comment by heyjcollins** [comment]
Perfecto!

Sent from my iPhone

On Feb 25, 2019, at 2:23 PM, Paul Warren <notifications@github.com> wrote:

Hi @heyjcollins <https://github.com/heyjcollins>,

Here are some commands for backing-up and deleting the nfs-brokerSQL
database from an internal MySQL server.

   1. bosh -d cf ssh database
   2. /var/vcap/packages/pxc/bin/mysqldump
   --defaults-extra-file=/var/vcap/jobs/pxc-mysql/config/mylogin.cnf
   nfs-broker > nfs.sql (to dump the database to a file)
   3. /var/vcap/packages/pxc/bin/mysql
   --defaults-extra-file=/var/vcap/jobs/pxc-mysql/config/mylogin.cnf -e "DROP
   DATABASE nfs-broker;" (to delete the database)

These commands assume that no customization has been performed by the
operator (such as renaming the database instance or the nfs-broker
database). If the operator is using an external database, they will have to
connect to it using their existing credentials and perform the
corresponding steps.

Let us know if you have more questions.

Regards
Paul and @davewalter <https://github.com/davewalter>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cloudfoundry/cf-deployment/pull/716#issuecomment-467208473>,
or mute the thread

**Comment by ab-pivot** [comment]
This doesn't have to be a breaking change. It looks like the only breaking change is `operations/experimental/enable-nfs-volume-service-credhub.yml` and instead of deletion we can replace inlined content with deprication comment.

**Pull request merged**
