### PR TITLE
Add ops-file to enable app log rate limiting

### PR DESCRIPTION
**Pull request by mariash**
### WHAT is this change about?

Add an ops-file that allows Alana to set the application log rate limit on her foundation. By default app log rate limiting is disabled (value 0).

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

This helps Alana to set limit on a noisy neighbor in the platform. If application is writing a lot of logs that affects the pipeline of logs sent to loggregator then other apps might see their logs being dropped.

### Please provide any contextual information.

https://www.pivotaltracker.com/story/show/170087515

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES
- [X] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [X] NO

### How should this change be described in cf-deployment release notes?

Added an ops-file to enable application log rate limiting.

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [X] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [X] GA'd feature/component

### Please provide Acceptance Criteria for this change?

1. Apply provided ops file and set `app_log_rate_limit` variable to 100.
2. Push an app that logs lines in a loop, e.g. modify https://github.com/cloudfoundry/grace to write in loop.
3. Tail logs of grace app. See that after 100 messages it will start rate limiting the log output and they will appear slower. 

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@cf-diego

### CODE REVIEW

**Comment by acosta11** [comment]
Hi Maria,

The PR notes the feature is GA'd, but the property appears to be experimental per [the rep spec](https://github.com/cloudfoundry/diego-release/blob/b7eb3c66ca702b2ea73465947900737fffb94303/jobs/rep/spec#L212), so we would like to put the ops file into the [experimental directory](https://github.com/cloudfoundry/cf-deployment/tree/develop/operations/experimental)  until the property is GA'd in the Diego bosh release.

Similarly, we found an operation for the windows2019 cell in [one of the tracker story's comments](https://www.pivotaltracker.com/story/show/170087515/comments/209593254). Do we want to have a separate ops-file to enable the feature for windows as well?

Thanks,
Andrew and Dave (@davewalter )

**Comment by mariash** [comment]
@acosta11 @davewalter sounds like a good idea to put those files in experimental folder. I would add a windows 2019 ops file as well.

**Comment by davewalter** [comment]
@mariash do you have time to make these changes to the PR, or are you OK with us doing the work when we get around to it?

Regards,
Dave and Sebastian (@vitreuz)

**Comment by mariash** [comment]
@davewalter if you guys can do it that would be great we have a chore scheduled for this work but did not get to it yet. https://www.pivotaltracker.com/story/show/170690217

**Pull request merged**
