### PR TITLE
Feat: Send logs and metrics to Log Cache using mTLS

### PR DESCRIPTION
**Pull request by Benjamintf1**
### WHAT is this change about?

Aggregate drains now uses mututal tls for log-cache connections

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

It makes log-cache more secure

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [x] YES
- [ ] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [x] NO

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [x] GA'd feature/component

### Please provide Acceptance Criteria for this change?

Log cache continues to work

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### CODE REVIEW

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/loggregator-agent-release/releases/tag/v7.2.0 Ready to merge as soon as this release is in

**Comment by Benjamintf1** [comment]
(Actually might want to check this doesn't cause downtime)

**Comment by Benjamintf1** [comment]
If log-cache is last, then it's no downtime, if it isn't we might want to wait to merge this.

**Comment by ctlong** [comment]
@Benjamintf1 maybe we should stage this change in two PRs: 1) add the certificates to the syslog binding cache, and 2) remove the `drain_ca_cert` property from the syslog agents.

That would eliminate any potential downtime, right?

**Comment by Benjamintf1** [comment]
That's not the problem. The problem is, if we roll log-cache before say, diego-cells/etc, then old syslog-agents(that can't get the *client* information) would start failing. 

The ca cert thing should be fine I believe. At least, mostly. New agents will get the new ca through the new endpoint alongside the client creds. It's if log-cache starts enforcing mtls before the agents have mtls that's the problem.

**Comment by ctlong** [comment]
The deployment order appears to be:

```
$ cat cf-deployment.yml | yq '.instance_groups.[] | .name'
smoke-tests
nats
database
diego-api
uaa
singleton-blobstore
api
cc-worker
scheduler
router
tcp-router
log-cache
doppler
diego-cell
log-api
credhub
rotate-cc-database-key
```

That means that the Syslog Binding Cache (on `scheduler`) should be updated to start serving a Log Cache address with mTLS prior to the Log Cache Syslog Server (on `log-cache`) requiring mTLS. However, that's only a small time gap and I think most Syslog Agents (added on to every instance) only poll the Syslog Binding Cache every 30 seconds, so this could result in some amount of log downtime in Log Cache. It's only on the one upgrade for a small amount of time though, and Log Cache is meant to be transient, so I think this is fine.

**Review by ctlong — APPROVED** [review]

**Pull request merged**
