### PR TITLE
log-cache-expvar-forwarder -> prom_scraper

### PR DESCRIPTION
**Pull request by johannaratliff**
[#162397765]

Signed-off-by: Johanna Ratliff <josmith@pivotal.io>

### Is this a PR to [the develop branch](https://github.com/cloudfoundry/cf-deployment/tree/develop) of cf-deployment?

Yes

### WHAT is this change about?

Removing hand rolled log-cache-expvar-forwarder job to be replaced by standardized `prom_scraper` job in loggregator-agent-release.

### WHY is this change being made (What problem is being addressed)?

Better to use a standardized scrape and dump to loggregator. Smaller manifest as a benefit.

### Please provide contextual information.

https://www.pivotaltracker.com/story/show/162397765

### Has a cf-deployment including this change passed our [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [x] YES 
- [ ] NO

### How should this change be described in cf-deployment release notes?

_Something brief that conveys the change and is written with the Operator audience in mind. 
See [previous release notes](https://github.com/cloudfoundry/cf-deployment/releases) for examples._

Removing `log-cache-expvar-forwarder` job to be replaced by standardized `prom_scraper` job in `loggregator-agent-release`.

### Does this PR introduce a breaking change? 

No. Blackbox jobs against log-cache might see a blip between the addition of prom_scraper and the removal of expvar-forwarder. But the scraped metrics are only for health endpoint and log-cache meta information. 

This will require log-cache `v2.3` for jobs to serve the prometheus `/metrics` endpoint.

### Will this change increase the VM footprint of cf-deployment?

- [ ] YES --- does it really have to?
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [x] GA'd feature/component

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
/cc @rheaton @jtuchscherer

### CODE REVIEW

**Comment by ab-pivot** [comment]
Hi @johannaratliff 

It looks like #162397765 has been rejected. Is this change ready for us to pull in?

**Comment by jtuchscherer** [comment]
Thanks @ab-pivot for following up. No, this change is not ready to pull in. It currently only works in a deployment with one log-api VM. We will fix this some time this week.

**Comment by cdutra** [comment]
Hi @jtuchscherer, is this fixed for multiple log-api VMs? Thanks!

**Comment by jtuchscherer** [comment]
@cdutra It has been fixed, but we haven't cut a release yet.
cc @toddboom

**Comment by jtuchscherer** [comment]
Created a story here: https://www.pivotaltracker.com/story/show/165236234

**Comment by toddboom** [comment]
@cdutra @ab-pivot We just cut Log Cache v2.3.0, so this PR (in addition to #756) can be merged now (and probably should be since they the new version of log cache might break cf-d).

Please let us know if you have any questions.

/cc @colins @rheaton

**Comment by cdutra** [comment]
@toddboom For more context: https://cloudfoundry.slack.com/archives/CBFB7NP9B/p1556143623002000

This is a breaking change for us and can only be merged for next major release.

**Comment by acosta11** [comment]
Merged manually in https://github.com/cloudfoundry/cf-deployment/commit/fa4b10e0dbf36b9f9fc594ed35cea75256048441 with a fix for the unit tests in https://github.com/cloudfoundry/cf-deployment/commit/3a4d294339f4dde48a1416741d2e8bb3da177e83 as part of the v10 release.

**Pull request closed without merging**
