### PR TITLE
Use bosh-dns-aliases to allow pre-existing BOSH DNS addons

### PR DESCRIPTION
**Pull request by drnic**
* [ ] waiting for https://github.com/cloudfoundry/bosh-dns-aliases-release/pull/3 to be accepted/merged
* [ ] waiting for v0.0.2 of https://github.com/cloudfoundry/bosh-dns-aliases-release
* [ ] update PR to use 0.0.2

To test this PR today, you'll need to use a dev release based off  https://github.com/cloudfoundry/bosh-dns-aliases-release/pull/3

### CODE REVIEW

**Comment by drnic** [comment]
Fixed master -> develop.

I will investigate " FAIL -  scripts/test-experimental-ops.sh  -  operations/experimental/use-bosh-dns-aliases.yml is NOT tested in scripts/test-experimental-ops.sh"

**Comment by dsabeti** [comment]
Thanks @drnic. We'll look at merging this PR once the necessary changes have been made to bosh-dns-aliases-release. Could you help us out by pinging this thread once that happens?

**Comment by drnic** [comment]
Yep I’ll track the dependencies thru to completion.

________________________________

**Comment by drnic** [comment]
I'm going to close this.  I'll solve this problem by changing my deployment of CFCR to use manifest addons like CF deployment does. https://github.com/drnic/kubo-deployment/blob/cfcr-simpler-times/manifests/cfcr.yml#L26-L42

**Pull request closed without merging**
