### PR TITLE
Remove skip_cert_verify in cf-deployment.yml

### PR DESCRIPTION
**Pull request by mkocher**
We think secure by default is a better option for cf-deployment.yml. There are still ops files in the repo which skip cert verification.

- If your deployment does not have a trusted certificate on the load
  balancer and you would like to run the smoke tests you can use the
  new ops file called disable-smoke-test-tls-validation.yml.

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES
- [X] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [X] YES - please choose the category from below. Feel free to provide additional details.
- [ ] NO

> **Types of breaking changes:**
> 6. requires out-of-band manual intervention on the part of the operator
> 7. modifies the ops-file path, changes the type, changes the values or removes ops-files from the following folders
>    - `./operations/` or `./operations/experimental`
>    - `./addons`
>    - `./backup-and-restore/`
>
> _If you're promoting an experimental Ops-file (or removing one), Please follow the [Ops-file workflows](https://github.com/cloudfoundry/cf-deployment/blob/main/ops-file-promotion-workflow.md)._

> Ops files changes in the following folders are considered as NON BREAKING CHANGES
> `./community`, `./example-vars-files`, `./test`

### How should this change be described in cf-deployment release notes?

cf-deployment.yml no longer skips some certificate validation for inter-component communication and the smoke tests. If you are using bosh & credhub to generate these certificates this change should not affect anything other than smoke tests. 

- If your deployment does not have a trusted certificate on the load
  balancer and you would like to run the smoke tests you can use the
  new ops file called disable-smoke-test-tls-validation.yml.

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [X] YES - New ops file as noted above.
- [ ] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [ ] GA'd feature/component

### Please provide Acceptance Criteria for this change?

- verify that smoke tests now fail if using an untrusted certificate authority. 
- verify skip cert verify is no longer present in cloud-controller and traffic-controller configuration yml files on the bosh deployed instances.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
@acrmp @ctlong @davewalter 
cc @cloudfoundry/cf-capi as this affects cloud controller communication

### CODE REVIEW

**Review by ctlong — APPROVED** [review]
Thanks!

**Comment by davewalter** [comment]
@mkocher @acrmp @ctlong This change appears to have caused issues when creating service brokers. For example, see [this failure](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/windows-cats/builds/526#L61f90e46:370) from CI:

```
[2022-02-07 20:40:35.36 (UTC)]> cf create-service-broker CATS-12-BRKR-CH-1ecf0c25661453c2 a-user a-password https://CATS-12-BRKR-CH-1ecf0c25661453c2.wenge.cf-app.com --space-scoped 
Creating service broker CATS-12-BRKR-CH-1ecf0c25661453c2 in org CATS-12-ORG-045bd123c4e9fda2 / space CATS-12-SPACE-f35151ce570cfa0b as CATS-12-USER-58f2c7f96cb5c2be...
FAILED
Job (03aed068-7ee0-4a4a-b2fe-039ce3f0099d) failed: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)
```

**Comment by tcdowney** [comment]
Here's a related issue for what @davewalter is seeing:
https://github.com/cloudfoundry/cloud_controller_ng/issues/825

The space scoped broker problem has historically been a blocker for removing `skip_cert_verify` from Cloud Controller. 😔

**Comment by ctlong** [comment]
Good call out @davewalter!

Thanks for the context @tcdowney!

Given all that, I reverted the PR. We may still be able to remove some `skip_cert_verify` properties, but it sounds like an across-the-board change is not in the cards

**Pull request merged**
