### PR TITLE
Consolidate VMs (implements #173)

### PR DESCRIPTION
**Pull request by emalm**
- Moves ssh_proxy job to router instance-group
- Moves cc_uploader job to api instance-group
- Moves file_server job to api instance-group
- Consolidates remaining jobs from cc-bridge, cc-clock, and diego-brain instance-groups (cloud_controller_clock; nsync and tps; auctioneer) on new scheduler instance-group

### CODE REVIEW

**Comment by dsabeti** [comment]
Hey @ematpl, thanks for the PR. I'll prioritize it to get reviewed, but it might not be for a week or two, since we're focusing on uptime measurements right now. Do you need this PR to get merged more quickly than that?

**Comment by ematpl** [comment]
Thanks, @dsabeti, this isn't urgent by any means. I just got a bee in my bonnet about it yesterday evening and drove it out.

**Comment by selzoc** [comment]
@ematpl looks like there is an issue with the ops file unit tests, can you take a look and update this pr so that the check passes?

**Comment by selzoc** [comment]
@ematpl Thanks for pointing our our doc gap!  We just added most of these yesterday and hooked them up to github.  Please check the document now and let me know if it's unclear.

**Comment by ematpl** [comment]
Thanks, @selzoc ! Looks good, I'll try out the test script.

**Comment by ematpl** [comment]
@selzoc Units have now passed on the latest commit.

**Comment by emalm** [comment]
Thanks, @selzoc !

**Pull request merged**
