### PR TITLE
ci(pull-requests): Don't require reviews to fail PRs made against main

### PR DESCRIPTION
**Pull request by ctlong**
### WHAT is this change about?

We currently only use these PR resources to error if the main branch is the base branch of the PR. Since presence of a PR to main is all that we care about, and the contents of the PR are never examined, let alone run, we should be able to disregard the requirements for reviews in this case.

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

The two CI jobs using these resources exist for the sole purpose of alerting PR creators and approvers that a PR has been incorrectly made against main instead of develop. Currently, a PR approval is required to trigger the two jobs, which means that it's initially on approvers to catch the incorrect base branch. I've missed that mistake two or three times in the past two weeks, and it's been causing me frustration because, after approving a PR, I then have to go back and explain that the base branch is wrong, which usually requires a rebase to fix, which requires a new PR approval...

### Please provide any contextual information.

Ever since we changed the default branch of CATs and CF-D from develop to main (for branch protection reasons IIRC), probably 50% of new PRs have been accidentally made against main. That's despite clear messages in the PR templates to only create PRs against develop.

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES
- [x] NO - just a CI change

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [x] NO

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [ ] GA'd feature/component

### Please provide Acceptance Criteria for this change?

When a PR is made against CF-D or CATs' `main` branch, the fail-prs-to-cats-main / fail-prs-to-cf-deployment-main job will immediately run and mark the PR as failing this check.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

None

### CODE REVIEW

**Comment by davewalter** [comment]
Is the approval requirement currently causing problems? I am concerned about the possibility of a PR accidentally being merged if it is removed.

**Comment by chombium** [comment]
@ctlong, I agree with @davewalter. Tbh, I don't know what's the process for merging develop in main. If there is some kind of automation, some kind of ci/cd pipeline that checks everything is all right and can be merged and the only way of merging things is through this pipeline, than we might do that, but I still think that it doesn't hurt if someone takes a look at the changes.

**Comment by ctlong** [comment]
@davewalter @chombium to be clear this does not change the majority of CF-D and CATs PR pipelines, and in fact only impacts the following two jobs:
* [fail-prs-to-cf-deployment-main](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/pull-requests/jobs/fail-prs-to-cf-deployment-main/builds/2)
* [fail-prs-to-cats-main](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/pull-requests/jobs/fail-prs-to-cats-main/builds/20)

Ever since we changed the default branch of CATs and CF-D from `develop` to `main` (for branch protection reasons IIRC), probably 50% of new PRs have been accidentally made against `main`. That's despite clear messages in the PR templates to only create PRs against `develop`.

The two jobs that I mentioned above exist for the sole purpose of alerting PR creators and approvers that a PR has been incorrectly made against `main` instead of `develop`. Currently, a PR approval is required to trigger the two jobs, which means that it's initially on approvers to catch the incorrect base branch. I've missed that mistake two or three times in the past two weeks, and it's been causing me frustration because, after approving a PR, I then have to go back and explain that the base branch is wrong, which usually requires a rebase to fix, which requires a new PR approval...

That's not to mention the risk that an approver merges a PR before the jobs above mark it as incorrect, not realizing it's made against `main` until it's too late. This is a more annoying problem to fix than if unit tests aren't passing. Also, the security risks that caused us to initially require approvals to run PRs through CI shouldn't apply here, because these two jobs don't actually run, or interact with, the PR code.

**Comment by chombium** [comment]
@ctlong thanks for the detailed clarification. I really like this idea and we should do it to the other repos as well. 

I've always hated it that when I open a PR in other CF repos, I have to wait for an approver to let the PR validation run. Sometimes I've waited at least a day because of shifted time zones and working hours, and sometimes even more. I really like the idea when someone opens a PR to be immediately informed about the state of the PR.

**Pull request merged**
