### PR TITLE
Bump bits-service to version 1.6.0

### PR DESCRIPTION
**Pull request by petergtz**
This release includes a more complete set of metrics emitted to statsd.

### CODE REVIEW

**Comment by dsabeti** [comment]
Hi @petergtz. I'm actually a bit surprised that we're not automatically updating this release. I'm going to repurpose this PR to make a Concourse job to auto-update.

**Comment by petergtz** [comment]
@dsabeti 

> Hello friend, it looks like your pull request has failed one or more of our checks. Please take a look! 👀

Not sure, what exactly failed here, because all checks seem to be green. Or should we ignore this for now?

**Comment by SocalNick** [comment]
@dsabeti bump, we’d like to get this version of bits-service in CF-D

**Comment by petergtz** [comment]
Closing as this was done in other commits:
- https://github.com/cloudfoundry/cf-deployment/commit/74bd5d01441dfcb34d5158d812ac04964197825a
- https://github.com/cloudfoundry/cf-deployment/commit/04416f95b11386320fd8829dcb02f7f46780faf4

**Pull request closed without merging**
