### PR TITLE
Add consumes/provides for mapfs

### PR DESCRIPTION
**Pull request by winkingturtle-vmw**
## Please take a moment to review the questions before submitting the PR

🚫 We only accept PRs to develop branch. If this is an exception, please specify why 🚫

### WHAT is this change about?

Adding a consumes/provides will make it possible to consume this release from another job. We need to add the same job in an isolation-segment which requires us to have this change.

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

Alana is unable to use the same in an isolation-segment

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [x] YES
- [ ] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [x] NO

> **Types of breaking changes:**
> 1. **causes app or operator downtime**
> 2. increases VM footprint of cf-deployment - e.g. new jobs, new add ons, increases # of instances etc.
> 3. modifies, deletes or moves the name of a job or instance group in the main manifest
> 4. modifies the name or deletes a property of a job or instance group in the main manifest
> 5. changes the name of credentials in the main manifest
> 6. requires out-of-band manual intervention on the part of the operator
> 7. modifies the ops-file path, changes the type, changes the values or removes ops-files from the following folders
>    - `./operations/` or `./operations/experimental`
>    - `./addons`
>    - `./backup-and-restore/`
>
> _If you're promoting an experimental Ops-file (or removing one), Please follow the [Ops-file workflows](https://github.com/cloudfoundry/cf-deployment/blob/main/ops-file-promotion-workflow.md)._

> Ops files changes in the following folders are considered as NON BREAKING CHANGES
> `./community`, `./example-vars-files`, `./test`

### How should this change be described in cf-deployment release notes?

> _Something brief that conveys the change and is written with the **persona (Alana, Cody...)** in mind. See [previous release notes](https://github.com/cloudfoundry/cf-deployment/releases) for examples._

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [x] GA'd feature/component

### Please provide Acceptance Criteria for this change?

> _Please specify either bosh cli or cf cli commands for our team (and cf operators) to verify the changes._

> _Few examples_
> 1. For a PR with a new job in the manifest, `bosh instances` can verify the job is running after upgrade. You can provide additional commands to verify the job is running as specified.
> 2. For a PR with new variables, `bosh variables | grep <var-name>` command can verify the variable exists. This is the simplest varification but you can also provide additional commands to test that the variable holds the desired value.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@ameowlia

### CODE REVIEW

**Comment by winkingturtle-vmw** [comment]
Requesting review from @cloudfoundry/wg-app-runtime-deployments-cf-deployment-approvers

**Comment by davewalter** [comment]
@winkingturtle-vmw Could you please provide more detail about the upcoming change to isolation segments that requires this change? Would it be possible for this change to be included in the ops-file that adds the isolation segment?

**Comment by ameowlia** [comment]
👋 Hi @davewalter, 

We have been gifted responsibility for the volume service releases. In the nfs-volume-service-release pipeline we need to run tests against two different nfs configurations (ldap and non-ldap). In order to only use one environment, we deploy the non-ldap configuration on the normal CF diego cells, and we deploy the ldap config on an iso-seg. We are using the isolation segment configs from cf-d, so the isolated cells are in the same bosh deployment as the normal cells. 

In this deployment setup there is a mapfs job deloyed on two different instance groups. Bosh links doesn't like this, so we need to define explicit provides/consumes links.

We could maintain our own opsfile that does this, but we would like to minimize the amount of things we own, so we hoped that we could make the change here. This would not change the behavior for anyone currently using this opsfile. This change would allow users like us to deploy volume services on isolation-segments as well.

**Comment by davewalter** [comment]
Hi @ameowlia, 👋 

Thanks for the context. I can definitely appreciate your desire to not have to maintain a custom ops-file to apply this change, but my concern is that it is only required for testing and I am worried that it would change how users would consume the mapfs link in the (admittedly unlikely) event that they have a release that also makes use of it.

**Comment by ameowlia** [comment]
👍 fair, fair. I'll close this and we will maintain our own opsfile.

**Pull request closed without merging**
