### PR TITLE
consistent 'default' name for all things: 'private' network now 'default'

### PR DESCRIPTION
**Pull request by drnic**
I've sanity tested this change by upgrading my cloud-config + deploying: all ok.

### CODE REVIEW

**Comment by drnic** [comment]
@dsabeti ETA for merging? 

https://github.com/cloudfoundry-community/docker-boshrelease/pull/79

**Comment by jaresty** [comment]
Hey @drnic,

Thanks for this PR!  I'm looking forward to merging it.  We noticed three kinds of changes in this PR:

1. The rename of the private network to default
2. The addition of a public network to the bosh-lite cloud config
3. The addition of a default VM type to bosh-lite

We are fine with (1) but are unsure about (2) and (3).   Can you please explain the rationale for including those two additional kinds of changes in this PR?  Would you be open to making separate PRs for those two changes?

Thank you.

**Comment by dsabeti** [comment]
@jaresty `bbl` actually gives you a [default vm type](https://github.com/cloudfoundry/bosh-bootloader/blob/master/cloudconfig/cloud_config_templates.go#L35) in your cloud-config. It makes sense to have the same thing in the bosh-lite cloud-config.

As for the update to add a public network, it's a deviation from what `bbl` gives you. @drnic, I think it's probably best to start by discussing the use case for a separate "public" network and adding it to `bbl`. Can we pull out that part of the PR for now?

**Comment by jaresty** [comment]
@dsabeti That makes sense to me.  So the only outstanding question is:

@drnic: Are you OK with pulling the public network change out into its own PR?

**Comment by drnic** [comment]
Yeah the public bit can come out.

**Comment by drnic** [comment]
I've rebased against `develop` and updated the PR to merge into `develop`.

**Comment by staylor14** [comment]
Hi @drnic 

I merged this into develop with a modification to the bosh-lite default network range.  It was originally a /22 network.  You increased its size to /19.  I moved it down slightly from there to /20 since this is what bbl provides (hooray eventual consistency!)

Thanks much!
--Steve

**Comment by drnic** [comment]
@staylor14 lol I probably was having a brain fart moment and thinking I was reducing it. Thanks for fix.

**Pull request merged**
