### PR TITLE
Add a minimal deployment override file

### PR DESCRIPTION
**Pull request by menicosia**

### CODE REVIEW

**Comment by dsabeti** [comment]
Hey @menicosia. This ops file looks good, but I want to CI this properly in our pipeline somewhere. I'm prioritizing the story, along with stories to build out a pipeline, but it will probably be a little while before we get to it.

**Comment by menicosia** [comment]
How's it going with that ci? ;)

**Comment by menicosia** [comment]
By the way, I noticed with a recent release of cf-deployment, something breaks wrt to consul deployment. Unfortunately, I don't know anything about debugging consul, but it sounds like there's something that doesn't work now which did when I submitted this PR. :/

**Comment by dsabeti** [comment]
@menicosia Yeah, we have a lot of stuff in our backlog right now...

As for the consul error, do you want to post the error logs from the consul node? I can try to help you debug the issue.

**Comment by staylor14** [comment]
@menicosia, we're working on this story now. Just so we're forewarned/forearmed, at what stage does the error you're now seeing happen? Does it happen while BOSH is trying to start the job, or when BOSH is trying to interpolate the manifest or fill the templates?

Thanks.

**Pull request merged**
