### PR TITLE
Move metric store opsfile out of experimental

### PR DESCRIPTION
**Pull request by julian-zucker**
## Please take a moment to review the questions before submitting the PR

🚫 We only accept PRs to develop branch. If this is an exception, please specify why 🚫

### WHAT is this change about?

This adds a single node Metric Store to the CF Deployment.

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

As metric support is phased out of Log Cache, users will need a new store for firehose metrics. Metric Store aims to fill this need by connecting directly to the RLP, durably storing all metrics for a foundation, and providing a PromQL-compatible query interface to access them.

### Please provide any contextual information.

https://www.pivotaltracker.com/story/show/167953063

We are just about to cut an updated release (v1.2.0) that should probably be specified in the manifest before this is merged. However, as I anticipate this PR will generate some discussion, we're getting it up here early so that we can start talking about it sooner.

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES
- [x] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [x] YES
- [ ] NO

This change increases VM footprint of cf-deployment.

### How should this change be described in cf-deployment release notes?

Adds a Metric Store instance, which provides operators and users with a durable store of firehose metrics that can be queried via PromQL.

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [x] YES
- [ ] NO

This will add the `metric-store-release` BOSH release.

### Does this PR make a change to an experimental or GA'd feature/component?

- [x] experimental feature/component
- [ ] GA'd feature/component

### Please provide Acceptance Criteria for this change?

An admin user should be able to run the following curl command and see a sucessful response:

```
curl -H "Authorization: $(cf oauth-token)" -sS -G https://my.foundation.pivotal.io/api/v1/query --data-urlencode 'query=cpu`
```

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

/cc @colins @attack @hdub2 @josephgee @heidmotron @toddboom

### CODE REVIEW

**Comment by weymanf** [comment]
Hello. Should I close https://github.com/cloudfoundry/cf-deployment/pull/830? Since this looks like a duplicate?

**Comment by toddboom** [comment]
@weymanf I believe @julian-zucker closed it already. We opened a new PR to reduce the clutter, since it seems like the preferred path is to move the ops file out of experimental after talking to @Syerram a couple weeks ago.

**Comment by toddboom** [comment]
Also, we are just about to cut a new OSS release in the next few days, so we can probably wait to merge this until that is ready to go. It will allow us to clean up the ops file just a bit.

**Comment by weymanf** [comment]
Is this a GA'd (validated in your pipeline) version of the metrics-store?

**Pull request merged**
