### PR TITLE
Adds docker ops file

### PR DESCRIPTION
**Pull request by robbo10**
Signed-off-by: Steven Barry <sba30@allstate.com>

### What is this change about?
This change is to add `enable-docker.yml` ops-file which could be beneficial to the community for enabling docker.

_Describe the change and why it's needed._
For any developers who would like to `cf push` to CF with docker images instead of using buildpacks.  This change will give developers the choice of either:
1) Using Buildpacks
2) Using Docker images

### Please provide contextual information.

_Include any links to other PRs, stories, slack discussions, etc... that will help establish context._
For any developers who would like to `cf push` to CF with docker images instead of using buildpacks.  This change will give developers the choice of either:
1) Using Buildpacks
2) Using Docker images

### Has a cf-deployment including this change passed our [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [X ] YES 
-  [ ] NO

### How should this change be described in cf-deployment release notes?

_Something brief that conveys the change and is written with the Operator audience in mind. 
See [previous release notes](https://github.com/cloudfoundry/cf-deployment/releases) for examples._

New Ops-files
operations/enable-docker.yml
Deploy with this ops file to enable docker insecure registry on the garden job. 

### Does this PR introduce a breaking change? 

_Does this introduce changes that would require operators to take action in order to deploy without a failure?_

- [ ] YES 
- [ X] NO

### Will this change increase the VM footprint of cf-deployment?

- [ ] YES --- does it really have to?
- [ X] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [X] GA'd feature/component

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [ X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._
@sba30

### CODE REVIEW

**Comment by robbo10** [comment]
Changed to develop branch.

**Comment by ishustava** [comment]
Hey @robbo10, thanks for this PR!

As far as I know, docker is enabled in cf-deployment by default. Here are the relevant [docs](https://docs.cloudfoundry.org/adminguide/docker.html) on how to use it.

It looks like you are enabling insecure docker registries, which aren't enabled by default for security reasons. Are you looking to enable them with an ops file? 

We'd love to hear more about your use case and see if there's an alternate solution.

**Comment by robbo10** [comment]
Hey @ishustava , thanks for the clarification this makes sense.  Would it be possible for us to change the PR to be `enabling insecure docker registries`.  

Our use case for this is we host our own internal docker registry, with access to docker hub also being blocked for push/pull.  We want to offer more choice by giving developers the option to either cf push using buildpacks or using docker images.

We tested this method and it fitted our use case 😄

**Comment by ishustava** [comment]
Hey @robbo10,

Thanks for this context!

Are your internal docker registries deployed with a self-signed certificate? If not, there is already support for private/internal registries (documented [here](https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#private)) with a valid certificate for HTTPS traffic. If your certificates are signed by a custom CA, you can use [BOSH trusted certificates feature](https://bosh.io/docs/trusted-certs/) to install your custom CA on VMs.

Overall, `cf-deployment` as a product is going in a direction of secure-by-default, production-ready deployment, so I'd think we'll be reluctant to add an insecure feature. Especially since there is a documented way to use internal docker repos that are using signed certificates. 

cc @heyjcollins

**Comment by robbo10** [comment]
@ishustava - No problem we can close this PR, thanks for all the information, it will help us going forward 👍

**Comment by heyjcollins** [comment]
Hey @robbo10 - I'm going to close this PR as per above. Please feel free to reach out to us [on slack](https://cloudfoundry.slack.com/messages/C2U7KA7M4) if you need any support with the private internal registries.

**Pull request closed without merging**
