### PR TITLE
Remove operations/windows2016-cell.yml

### PR DESCRIPTION
**Pull request by aemengo**
* The referenced winc-release [2.0.0] is unsupported. Users should prefer
operations/windows2019-cell.yml

Signed-off-by: Anthony Emengo <aemengo@pivotal.io>

## Please take a moment to review the questions before submitting the PR

🚫 We only accept PRs to develop branch. If this is an exception, please specify why 🚫

### WHAT is this change about?

Remove opsfile for adding the older Windows Server 1709 cell

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [X] YES
- [ ] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [X] YES - please choose the category from below. Feel free to provide additional details.
- [ ] NO

Yes - remove support for an OS version

### How should this change be described in cf-deployment release notes?

Remove support for Windows Server 1709 cells

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [X] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [X] GA'd feature/component

### Please provide Acceptance Criteria for this change?

No A/C since this PR remove support for an OS version

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

@arjun024 @jfeeny @cloudfoundry/

### CODE REVIEW

**Comment by weymanf** [comment]
Hi. It looks like there are changes to our CI in this PR. We appreciate that you took the time to remove the 2016 items from our CI, but since we don't have proper guidelines for making PRs towards our CI folder I have to ask you to pull those changes. Thanks!

**Comment by arjun024** [comment]
@weymanf If we change the PR to have only changes to: `operations*.yml` and `operations/README.md`, would that be good?

**Comment by weymanf** [comment]
Yes everything except the `ci` folder. Theres also a section in the cf-deployment.yml with removing the bosh dns record that we want to take.

**Comment by arjun024** [comment]
@weymanf Done

**Comment by weymanf** [comment]
Since this is a breaking change. We will probably have it rolled in the next major release of CF-D.

Could yall please add back the changes to `cf-deployment.yml` (https://github.com/cloudfoundry/cf-deployment/blob/develop/cf-deployment.yml#L103) where yall deleted the bosh DNS for windows 2016? 

Sorry, for the confusion.

**Comment by arjun024** [comment]
@weymanf Done

**Comment by ericpromislow** [comment]
Hi @aemengo 

Thanks for submitting the PR.

We merged this manually because the PR was doing everything necessary except removing `operations/windows2016-cell.yml`.

You can see the commits [here](https://github.com/cloudfoundry/cf-deployment/commit/0823bbe6ae04ee13c3a86d18c72d8900a566eb65).

**Pull request closed without merging**
