### PR TITLE
Add an opsfile to enable perm service

### PR DESCRIPTION
**Pull request by oozie**
**Please do not merge!**

This ops file extends a CF deployment with the experimental PERM service and its related errands.

We'd love some feedback on what you expect from an experimental ops file. For example, at the moment we template in a variable called `perm_version` to allow for continuous change in our pipeline. Would you prefer that this was hardcoded to a particular version for the time being?

Is there any other information you'd like (e.g. a README) as part of this pull request to let others know how to use this ops file?

### CODE REVIEW

**Comment by dsabeti** [comment]
Hi @oozie, thanks for the PR and the questions about how to contribute ops-files. If you look at the failed build, you'll see that it's asking you to add some documentation in the [README for experimental ops-files](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/README.md).

As for the ops-file itself:
- Definitely add a hard-coded version of the perm-release into the ops-file. If your release is already on bosh.io, we can add automation to keep it up-to-date.
- It looks like this ops-file also enables TLS on the mysql cluster. I'm not exactly sure how the mysql configuration works, but if this requires that all other connections use TLS, it would probably be best to enable database TLS with a separate ops-file.
- It also seems like this ops-file depends on BOSH DNS. If so, let's make sure to document that.

**Comment by oozie** [comment]
We've broken out the MySQL TLS changes in to a different ops file. The variable names are interchangeable with the pxc ops files.

We're going to publish a release; please don't merge at least until then.

**Comment by oozie** [comment]
Successfully deployed locally.

@dsabeti we're ready to have this PR considered for a merge. Is there anything left for us to do?

**Comment by dsabeti** [comment]
@oozie, do y'all have your release published on bosh.io? If so, we'll automatically updated; otherwise, we'll need y'all to manually update it when you want new versions to get tested. Either way, I can prioritize this PR for merging.

**Comment by oozie** [comment]
@dsabeti ack. Please prioritize merging it and we'll reach out when we're on bosh.io.

**Comment by ishustava** [comment]
This PR is [now merged](https://github.com/cloudfoundry/cf-deployment/commits/develop).

**Pull request closed without merging**
