### PR TITLE
Add ops file to create autoscaler database for app-autoscaler deployment

### PR DESCRIPTION
**Pull request by aqan213**
### WHAT is this change about?
 Autoscaler has added a new feature to support MySQL database. To add the ops file to create autoscaler database for the autoscaler deployment. It is optional and only be used when customer would like to use cf mysql as autoscaler database.

### What customer problem is being addressed? Use customer persona to define the problem 

Autoscaler can use the mysql as the primary database and don't need to deploy and manage a postgres database.

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES
- [x] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [x] NO

### How should this change be described in cf-deployment release notes?

Add an ops file to create autoscaler database for autoscaler deeployment.

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [x] experimental feature/component
- [ ] GA'd feature/component

### Please provide Acceptance Criteria for this change?
Create a cf-deployment normally with `operations/experimental/set-autoscaler-db.yml` ops file. bosh ssh to the database vm and run mysq l -u autoscaler -p <autoscaler_database_password> to check if the autoscaler database is created in the mysql.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
@cdlliuy

### CODE REVIEW

**Comment by paulcwarren** [comment]
Apologies for the extremely tardy response times on this PR.

Based on comments that our engineers made on the story it looks like this optional ops file is actually dependent on the app autoscaler bosh release that isn't currently part of cf-d.  We would happily consider a PR that add that release as well as the autoscaler db in order to create a functionally complete ops file.  Otherwise, I think this is out of scope for us.

I will leave this open for a few days to allow you to comment if you feel very strongly that this should be included.  Otherwise, I will close it out presently.

**Comment by paulcwarren** [comment]
Ping.  Any comments on this @aqan213

**Comment by aqan213** [comment]
@paulcwarren Sorry for the delay to response here.  I thought it is easy to just add a database(database name, username and password) in the cf mysql database like CC etc. Is it necessary to add the app-autoscaler release into the cf deployment? thanks,

**Comment by aqan213** [comment]
@paulcwarren Sorry. Please ignore the above comments. I did not understand the problem at first. After discussion with autoscaler team, it will be great if we can add the app-autoscaler release to cf-d.   Then customers can deploy autoscaler along with cf-deployment if enabled it.  I will raise a PR to create an ops file to add the autoscaler release as well as autoscaler db. Thanks,

**Comment by paulcwarren** [comment]
Closing this and looking forward to the more holistic PR.

Many thanks.

**Pull request closed without merging**
