### PR TITLE
Add experimental ops file to add cflinuxfs4 stack

### PR DESCRIPTION
**Pull request by Gerg**
- Only adds cflinuxfs4 stack; does NOT make it the default stack
- Include buildpacks that currently support cflinuxfs4
- `cc/diego/droplet_destinations` and `cc/diego/lifecycle_bundles` both override default values from capi-release. In the long term, we should change those defaults in capi-release, rather than overriding in cf-deployment.

[#989]

### WHAT is this change about?

> Add experimental ops file to add cflinuxfs4 stack

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

> App developers need to move off of cflinuxfs3 before the backing ubuntu version goes out of support. They can't start moving their apps until cflinuxfs4 is available.

### Please provide any contextual information.

> #989

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

- [ ] YES
- [x] NO

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [x] NO

### How should this change be described in cf-deployment release notes?

> Add experimental ops file to add cflinuxfs4 stack

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [x] YES - please specify
- [ ] NO

Adds [cflinuxfs4](https://bosh.io/releases/github.com/cloudfoundry/cflinuxfs4-release?all=1).

### Does this PR make a change to an experimental or GA'd feature/component?

- [x] experimental feature/component
- [ ] GA'd feature/component

### Please provide Acceptance Criteria for this change?

Using the python sample app from CATS:
```
$ cf push python -s cflinuxfs4
...
```

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

> @ryanmoran @ctlong @arjun024 @brayanhenao

### CODE REVIEW

**Comment by Gerg** [comment]
cc @jochenehret @stephanme

**Comment by ryanmoran** [comment]
cc/ @cloudfoundry/wg-app-runtime-interfaces-buildpacks-approvers

**Comment by stephanme** [comment]
@gerg: Do you have a specific reason for not adding the go-buildpack?

https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.10.0 supportes cflinuxfs4 according to release notes.

**Comment by ryanmoran** [comment]
> @Gerg: Do you have a specific reason for not adding the go-buildpack?
> 
> https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.10.0 supportes cflinuxfs4 according to release notes.

There was a packaging issue with that release. The buildpacks team is investigating and we should not include it until we resolve the issue.

**Comment by jochenehret** [comment]
What about the `cc.diego.docker_staging_stack` configuration? When can we change this to cflinuxfs4?
https://github.com/cloudfoundry/cf-deployment/blob/84542677fcbe1fbe6b672a155b49d2697ef410aa/cf-deployment.yml#L923

**Comment by jochenehret** [comment]
Follow-ups (I can do this):

- add cflinuxfs4 release to inputs: https://github.com/cloudfoundry/cf-deployment/blob/main/ci/input/inputs.yml
- update "update-releases" pipeline (recreate from template): https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/update-releases?group=update-base-releases
- add new ops file to "experimental" deploy job
- add cflinuxfs4 as additional stack to "experimental" CATs config: https://github.com/cloudfoundry/relint-envs/blob/main/environments/test/hermione/integration_config.json

**Comment by Gerg** [comment]
@jochenehret Based on #989, my understanding is that we will have (at least) two experimental ops files:
1. Add `cflinuxfs4` as a possible stack
2. Change `cflinuxfs4` to be the default stack (& the docker staging stack?)

I can add that second ops file to this PR, if desired.

**Comment by Gerg** [comment]
I went ahead and opened a new PR to make the default stack `cflinuxfs4`: #1011

**Pull request merged**
